export const INSTALL = 'eon/INSTALL';
export const INSTALL_SUCCESS = 'eon/INSTALL_SUCCESS';
export const INSTALL_FAIL = 'eon/INSTALL_FAIL';
export const UNINSTALL = 'eon/UNINSTALL';
export const UNINSTALL_SUCCESS = 'eon/UNINSTALL_SUCCESS';
export const UNINSTALL_FAIL = 'eon/UNINSTALL_FAIL';

export const EON_STATE = 'eon/EON_STATE';
export const EON_STATE_OPEN = 'eon/EON_STATE_OPEN';
export const EON_STATE_CLOSE = 'eon/EON_STATE_CLOSE';
export const EON_STATE_RESPONSE = 'eon/EON_STATE_RESPONSE';
export const EON_STATE_FAIL = 'eon/EON_STATE_FAIL';

export const GET_FINGERPRINT = 'eon/GET_FINGERPRINT';
export const GET_FINGERPRINT_OPEN = 'eon/GET_FINGERPRINT_OPEN';
export const GET_FINGERPRINT_CLOSE = 'eon/GET_FINGERPRINT_CLOSE';
export const GET_FINGERPRINT_RESPONSE = 'eon/GET_FINGERPRINT_RESPONSE';
export const GET_FINGERPRINT_FAIL = 'eon/GET_FINGERPRINT_FAIL';

export const CONNECT_SSH = 'eon/CONNECT_SSH';
export const CONNECT_SSH_SUCCESS = 'eon/CONNECT_SSH_SUCCESS';
export const CONNECT_SSH_FAIL = 'eon/CONNECT_SSH_FAIL';

export const SSH_COMMAND = 'eon/SSH_COMMAND';
export const SSH_COMMAND_SUCCESS = 'eon/SSH_COMMAND_SUCCESS';
export const SSH_COMMAND_RESPONSE = 'eon/SSH_COMMAND_RESPONSE';
export const SSH_COMMAND_FAIL = 'eon/SSH_COMMAND_FAIL';

export const STOP_POLLING = 'eon/STOP_POLLING';