export const INSTALL = 'eon/INSTALL';
export const INSTALL_SUCCESS = 'eon/INSTALL_SUCCESS';
export const BOOTSTRAP_EON = 'eon/BOOTSTRAP_EON';
export const CONNECT = 'eon/CONNECT';
export const CONNECT_FAILED = 'eon/CONNECT_FAILED';
export const CONNECTED = 'eon/CONNECTED';
export const MESSAGE_RECEIVED = 'eon/MESSAGE_RECEIVED';
export const MESSAGE = 'eon/MESSAGE';
export const DISCONNECT = 'eon/DISCONNECT';
export const DISCONNECTED = 'eon/DISCONNECTED';
export const PRIVATE_KEY_INSTALLED = 'eon/PRIVATE_KEY_INSTALLED';
export const INSTALL_FAIL = 'eon/INSTALL_FAIL';
export const UNINSTALL = 'eon/UNINSTALL';
export const UNINSTALL_SUCCESS = 'eon/UNINSTALL_SUCCESS';
export const UNINSTALL_FAIL = 'eon/UNINSTALL_FAIL';
export const CHANGE_TAB = 'eon/CHANGE_TAB';
export const AUTH_REQUEST = 'eon/AUTH_REQUEST';
export const AUTH_REQUEST_SUCCESS = 'eon/AUTH_REQUEST_SUCCESS';
export const AUTH_REQUEST_FAIL = 'eon/AUTH_REQUEST_FAIL';
export const HIDE_ROUTE = 'eon/HIDE_ROUTE';
export const SHOW_ROUTE = 'eon/SHOW_ROUTE';
export const SHOW_ROUTE_SUCCESS = 'eon/SHOW_ROUTE_SUCCESS';
export const SHOW_ROUTE_FAILED = 'eon/SHOW_ROUTE_FAILED';
export const OPEN_DRIVE = 'eon/OPEN_DRIVE';
export const CLOSE_DRIVE = 'eon/CLOSE_DRIVE';

export const API_REQUEST = 'eon/API_REQUEST';
export const API_REQUEST_SUCCESS = 'eon/API_REQUEST_SUCCESS';
export const API_REQUEST_FAIL = 'eon/API_REQUEST_FAIL';

export const EON_STATE = 'eon/EON_STATE';
export const EON_STATE_OPEN = 'eon/EON_STATE_OPEN';
export const EON_STATE_CLOSE = 'eon/EON_STATE_CLOSE';
export const EON_STATE_RESPONSE = 'eon/EON_STATE_RESPONSE';
export const EON_STATE_FAIL = 'eon/EON_STATE_FAIL';
export const EON_STATE_FATAL = 'eon/EON_STATE_FATAL';

export const GET_FINGERPRINT = 'eon/GET_FINGERPRINT';
export const GET_FINGERPRINT_OPEN = 'eon/GET_FINGERPRINT_OPEN';
export const GET_FINGERPRINT_CLOSE = 'eon/GET_FINGERPRINT_CLOSE';
export const GET_FINGERPRINT_RESPONSE = 'eon/GET_FINGERPRINT_RESPONSE';
export const GET_FINGERPRINT_FAIL = 'eon/GET_FINGERPRINT_FAIL';

export const CONNECT_SSH = 'eon/CONNECT_SSH';
export const CONNECT_SSH_SUCCESS = 'eon/CONNECT_SSH_SUCCESS';
export const CONNECT_SSH_FAIL = 'eon/CONNECT_SSH_FAIL';

export const SHOW_COMMAND = 'eon/SHOW_COMMAND';
export const HIDE_COMMAND = 'eon/HIDE_COMMAND';
export const RUN_COMMAND = 'eon/RUN_COMMAND';
export const RUN_COMMAND_SUCCESS = 'eon/RUN_COMMAND_SUCCESS';
export const RUN_COMMAND_RESPONSE = 'eon/RUN_COMMAND_RESPONSE';
export const RUN_COMMAND_FAIL = 'eon/RUN_COMMAND_FAIL';

export const STOP_POLLING = 'eon/STOP_POLLING';

export const FETCH_AUTH_FILE = 'eon/FETCH_AUTH_FILE';
export const FETCH_AUTH_FILE_SUCCESS = 'eon/FETCH_AUTH_FILE_SUCCESS';
export const FETCH_AUTH_FILE_FAILED = 'eon/FETCH_AUTH_FILE_FAILED';

export const FETCH_DATA_PARAMS = 'eon/FETCH_DATA_PARAMS';
export const FETCH_DATA_PARAMS_SUCCESS = 'eon/FETCH_DATA_PARAMS_SUCCESS';
export const FETCH_DATA_PARAMS_FAILED = 'eon/FETCH_DATA_PARAMS_FAILED';

export const FETCH_PROFILE = 'eon/FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'eon/FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILED = 'eon/FETCH_PROFILE_FAILED';

export const FETCH_ROUTES = 'eon/FETCH_ROUTES';
export const FETCH_ROUTES_SUCCESS = 'eon/FETCH_ROUTES_SUCCESS';
export const FETCH_ROUTES_FAILED = 'eon/FETCH_ROUTES_FAILED';

export const FETCH_DEVICES = 'eon/FETCH_DEVICES';
export const FETCH_DEVICES_SUCCESS = 'eon/FETCH_DEVICES_SUCCESS';
export const FETCH_DEVICES_FAILED = 'eon/FETCH_DEVICES_FAILED';

export const FETCH_LOGS = 'eon/FETCH_LOGS';
export const FETCH_LOGS_SUCCESS = 'eon/FETCH_LOGS_SUCCESS';
export const FETCH_LOGS_FAILED = 'eon/FETCH_LOGS_FAILED';

export const FETCH_SEGMENTS = 'eon/FETCH_SEGMENTS';
export const FETCH_SEGMENTS_SUCCESS = 'eon/FETCH_SEGMENTS_SUCCESS';
export const FETCH_SEGMENTS_FAILED = 'eon/FETCH_SEGMENTS_FAILED';

export const FETCH_ANNOTATIONS = 'eon/FETCH_ANNOTATIONS';
export const FETCH_ANNOTATIONS_SUCCESS = 'eon/FETCH_ANNOTATIONS_SUCCESS';
export const FETCH_ANNOTATIONS_FAILED = 'eon/FETCH_ANNOTATIONS_FAILED';

export const FETCH_ROUTE_FILE_LINKS = 'eon/FETCH_ROUTE_FILE_LINKS';
export const FETCH_ROUTE_FILE_LINKS_SUCCESS = 'eon/FETCH_ROUTE_FILE_LINKS_SUCCESS';
export const FETCH_ROUTE_FILE_LINKS_FAILED = 'eon/FETCH_ROUTE_FILE_LINKS_FAILED';

export const FETCH_ROUTE_FILES = 'eon/FETCH_ROUTE_FILES';
export const FETCH_ROUTE_FILES_SUCCESS = 'eon/FETCH_ROUTE_FILES_SUCCESS';
export const FETCH_ROUTE_FILES_FAILED = 'eon/FETCH_ROUTE_FILES_FAILED';

export const DOWNLOAD_ROUTE = 'eon/DOWNLOAD_ROUTE';
export const DOWNLOAD_ROUTE_SUCCESS = 'eon/DOWNLOAD_ROUTE_SUCCESS';
export const DOWNLOAD_ROUTE_FAILED = 'eon/DOWNLOAD_ROUTE_FAILED';

export const DOWNLOAD_SEGMENT = 'eon/DOWNLOAD_SEGMENT';
export const DOWNLOAD_SEGMENT_SUCCESS = 'eon/DOWNLOAD_SEGMENT_SUCCESS';
export const DOWNLOAD_SEGMENT_FAILED = 'eon/DOWNLOAD_SEGMENT_FAILED';
