module.exports = {
  SCAN_NETWORK: 'scanner/SCAN_NETWORK',
  SCAN_NETWORK_COMPLETE: 'scanner/SCAN_NETWORK_COMPLETE',
  SCAN_NETWORK_COUNT: 'scanner/SCAN_NETWORK_COUNT',
  SCAN_NETWORK_PROGRESS: 'scanner/SCAN_NETWORK_PROGRESS',
  SCAN_NETWORK_RESULT: 'scanner/SCAN_NETWORK_RESULT',
  SCAN_NETWORK_PARTIAL_COMPLETE: 'scanner/SCAN_NETWORK_PARTIAL_COMPLETE',
  SCAN_NETWORK_FAIL: 'scanner/SCAN_NETWORK_FAIL',
  SCAN_NETWORK_RESET: 'scanner/SCAN_NETWORK_RESET',
  MAC_ADDRESS_REQUEST: 'scanner/MAC_ADDRESS_REQUEST',
  MAC_ADDRESS_SUCCESS: 'scanner/MAC_ADDRESS_SUCCESS',
  MAC_ADDRESS_ERROR: 'scanner/MAC_ADDRESS_ERROR',
  REMOVE_SCANNED_RESULT: 'scanner/REMOVE_SCANNED_RESULT',
  PINGED_EONS: 'scanner/PINGED_EONS'
}
