export const SCAN_NETWORK = 'scanner/SCAN_NETWORK';
export const SCAN_NETWORK_COMPLETE = 'scanner/SCAN_NETWORK_COMPLETE';
export const SCAN_NETWORK_COUNT = 'scanner/SCAN_NETWORK_COUNT';
export const SCAN_NETWORK_PROGRESS = 'scanner/SCAN_NETWORK_PROGRESS';
export const SCAN_NETWORK_RESULT = 'scanner/SCAN_NETWORK_RESULT';
export const SCAN_NETWORK_PARTIAL_COMPLETE = 'scanner/SCAN_NETWORK_PARTIAL_COMPLETE';
export const SCAN_NETWORK_FAIL = 'scanner/SCAN_NETWORK_FAIL';
export const SCAN_NETWORK_RESET = 'scanner/SCAN_NETWORK_RESET';
export const MAC_ADDRESS_REQUEST = 'scanner/MAC_ADDRESS_REQUEST';
export const MAC_ADDRESS_SUCCESS = 'scanner/MAC_ADDRESS_SUCCESS';
export const MAC_ADDRESS_ERROR = 'scanner/MAC_ADDRESS_ERROR';
export const REMOVE_SCANNED_RESULT = 'scanner/REMOVE_SCANNED_RESULT';

export const PINGED_EONS = 'scanner/PINGED_EONS';