export const INSTALL_FORK = 'tasks/INSTALL_FORK'
export const INSTALL_FORK_SUCCESS = 'tasks/INSTALL_FORK_SUCCESS'
export const INSTALL_FORK_RESPONSE = 'tasks/INSTALL_FORK_RESPONSE'
export const INSTALL_FORK_FAIL = 'tasks/INSTALL_FORK_FAIL'