export const TERMINAL_RESIZE = "terminal/RESIZE"
export const TERMINAL_COMMAND = "terminal/COMMAND"
export const TERMINAL_DISCONNECT = "terminal/DISCONNECT"
export const TERMINAL_CONNECT = "terminal/CONNECT"
export const TERMINAL_CONNECTED = "terminal/CONNECTED"
export const TERMINAL_ERROR = "terminal/ERROR"
export const TERMINAL_MESSAGE = "terminal/MESSAGE"